-- AlterTable
ALTER TABLE "Cliente" ADD COLUMN "telefone" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Cliente" ADD COLUMN "email" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Cliente" ADD COLUMN "empresa" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Cliente" ADD COLUMN "interesse" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Cliente" ADD COLUMN "valor" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Cliente" ADD COLUMN "origem" TEXT NOT NULL DEFAULT 'Manual';
ALTER TABLE "Cliente" ADD COLUMN "favorito" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Cliente" ADD COLUMN "quente" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Cliente" ADD COLUMN "ultimoContato" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Cliente" ADD COLUMN "proximoFollowUp" TEXT NOT NULL DEFAULT 'Hoje';
ALTER TABLE "Cliente" ADD COLUMN "tags" TEXT NOT NULL DEFAULT '[]';

-- CreateTable
CREATE TABLE "Nota" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "texto" TEXT NOT NULL,
    "tipo" TEXT NOT NULL DEFAULT 'nota',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "clienteId" INTEGER NOT NULL,
    CONSTRAINT "Nota_clienteId_fkey" FOREIGN KEY ("clienteId") REFERENCES "Cliente" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateIndex
CREATE INDEX "Nota_clienteId_idx" ON "Nota"("clienteId");
