BEGIN;

ALTER TYPE "ChaveFuncionalidade" ADD VALUE IF NOT EXISTS 'AI_COMMERCE';

CREATE TABLE "AICommerceSettings" (
  "id" SERIAL NOT NULL,
  "empresaId" INTEGER NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "mode" TEXT NOT NULL DEFAULT 'OFF',
  "mockEnabled" BOOLEAN NOT NULL DEFAULT false,
  "allowedToolsJson" TEXT NOT NULL DEFAULT '[]',
  "maxTools" INTEGER NOT NULL DEFAULT 5,
  "maxContextMessages" INTEGER NOT NULL DEFAULT 20,
  "maxProducts" INTEGER NOT NULL DEFAULT 3,
  "humanApprovalRequired" BOOLEAN NOT NULL DEFAULT true,
  "catalogVisibilityPolicy" TEXT NOT NULL DEFAULT 'PUBLISHED',
  "exactQuantityPolicy" TEXT NOT NULL DEFAULT 'HIDDEN',
  "stalePolicy" TEXT NOT NULL DEFAULT 'NEEDS_CONFIRMATION',
  "noPricePolicy" TEXT NOT NULL DEFAULT 'DO_NOT_QUOTE',
  "opportunityPolicy" TEXT NOT NULL DEFAULT 'DRAFT_ONLY',
  "handoffPolicy" TEXT NOT NULL DEFAULT 'HUMAN_ONLY',
  "retentionDays" INTEGER NOT NULL DEFAULT 30,
  "revision" INTEGER NOT NULL DEFAULT 1,
  "actorUsuarioId" INTEGER,
  "correlationId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AICommerceSettings_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "AICommerceSettings_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT "AICommerceSettings_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX "AICommerceSettings_empresaId_id_key" ON "AICommerceSettings"("empresaId", "id");
CREATE UNIQUE INDEX "AICommerceSettings_empresaId_key" ON "AICommerceSettings"("empresaId");
CREATE INDEX "AICommerceSettings_empresaId_enabled_mode_idx" ON "AICommerceSettings"("empresaId", "enabled", "mode");

CREATE TABLE "AICommerceRun" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT NOT NULL, "conversationId" INTEGER, "triggerMessageId" INTEGER, "idempotencyKey" TEXT NOT NULL, "mode" TEXT NOT NULL DEFAULT 'OFF', "state" TEXT NOT NULL DEFAULT 'IDLE', "status" TEXT NOT NULL DEFAULT 'STARTED', "policyVersion" TEXT NOT NULL DEFAULT 'ai-commerce-policy.v1', "messageRevision" TEXT, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" TIMESTAMP(3), "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceRun_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceRun_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceRun_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceRun_empresaId_triggerMessageId_fkey" FOREIGN KEY ("empresaId", "triggerMessageId") REFERENCES "MensagemCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceRun_empresaId_id_key" ON "AICommerceRun"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceRun_empresaId_runId_key" ON "AICommerceRun"("empresaId", "runId"); CREATE UNIQUE INDEX "AICommerceRun_empresaId_idempotencyKey_key" ON "AICommerceRun"("empresaId", "idempotencyKey"); CREATE INDEX "AICommerceRun_empresaId_conversationId_createdAt_idx" ON "AICommerceRun"("empresaId", "conversationId", "createdAt"); CREATE INDEX "AICommerceRun_empresaId_status_createdAt_idx" ON "AICommerceRun"("empresaId", "status", "createdAt"); CREATE INDEX "AICommerceRun_empresaId_retentionUntil_idx" ON "AICommerceRun"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceTurn" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT NOT NULL, "conversationId" INTEGER, "turnNumber" INTEGER NOT NULL DEFAULT 0, "state" TEXT NOT NULL DEFAULT 'DISCOVERY', "status" TEXT NOT NULL DEFAULT 'RECORDED', "decisionJson" TEXT, "toolResultsJson" TEXT, "latencyMs" INTEGER, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceTurn_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceTurn_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceTurn_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceTurn_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceTurn_empresaId_id_key" ON "AICommerceTurn"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceTurn_empresaId_runId_turnNumber_key" ON "AICommerceTurn"("empresaId", "runId", "turnNumber"); CREATE INDEX "AICommerceTurn_empresaId_conversationId_occurredAt_idx" ON "AICommerceTurn"("empresaId", "conversationId", "occurredAt"); CREATE INDEX "AICommerceTurn_empresaId_retentionUntil_idx" ON "AICommerceTurn"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceToolInvocation" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT, "turnId" TEXT, "conversationId" INTEGER, "name" TEXT NOT NULL DEFAULT 'unknown', "classification" TEXT NOT NULL DEFAULT 'READ', "status" TEXT NOT NULL DEFAULT 'RECORDED', "idempotencyKey" TEXT, "inputJsonSanitized" TEXT NOT NULL DEFAULT '{}', "outputJsonSanitized" TEXT, "errorCode" TEXT, "latencyMs" INTEGER, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceToolInvocation_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceToolInvocation_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceToolInvocation_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceToolInvocation_empresaId_turnId_fkey" FOREIGN KEY ("empresaId", "turnId") REFERENCES "AICommerceTurn"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceToolInvocation_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceToolInvocation_empresaId_id_key" ON "AICommerceToolInvocation"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceToolInvocation_empresaId_idempotencyKey_key" ON "AICommerceToolInvocation"("empresaId", "idempotencyKey") WHERE "idempotencyKey" IS NOT NULL; CREATE INDEX "AICommerceToolInvocation_empresaId_runId_occurredAt_idx" ON "AICommerceToolInvocation"("empresaId", "runId", "occurredAt"); CREATE INDEX "AICommerceToolInvocation_empresaId_name_status_idx" ON "AICommerceToolInvocation"("empresaId", "name", "status"); CREATE INDEX "AICommerceToolInvocation_empresaId_retentionUntil_idx" ON "AICommerceToolInvocation"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceDecision" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT NOT NULL, "turnId" TEXT, "conversationId" INTEGER, "intent" TEXT, "confidence" TEXT, "nextAction" TEXT, "missingInformationJson" TEXT, "requestedToolsJson" TEXT, "draftResponse" TEXT, "offerIdsJson" TEXT, "handoffReason" TEXT, "safetyFlagsJson" TEXT, "policyFlagsJson" TEXT, "decisionJson" TEXT NOT NULL DEFAULT '{}', "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceDecision_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceDecision_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDecision_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDecision_empresaId_turnId_fkey" FOREIGN KEY ("empresaId", "turnId") REFERENCES "AICommerceTurn"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDecision_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceDecision_empresaId_id_key" ON "AICommerceDecision"("empresaId", "id"); CREATE INDEX "AICommerceDecision_empresaId_runId_occurredAt_idx" ON "AICommerceDecision"("empresaId", "runId", "occurredAt"); CREATE INDEX "AICommerceDecision_empresaId_conversationId_occurredAt_idx" ON "AICommerceDecision"("empresaId", "conversationId", "occurredAt"); CREATE INDEX "AICommerceDecision_empresaId_retentionUntil_idx" ON "AICommerceDecision"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceDraft" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT NOT NULL, "conversationId" INTEGER NOT NULL, "decisionId" TEXT, "status" TEXT NOT NULL DEFAULT 'PENDING_APPROVAL', "textSanitized" TEXT, "offersJson" TEXT NOT NULL DEFAULT '[]', "questionsJson" TEXT NOT NULL DEFAULT '[]', "actionsJson" TEXT NOT NULL DEFAULT '[]', "warningsJson" TEXT NOT NULL DEFAULT '[]', "requiresHumanApproval" BOOLEAN NOT NULL DEFAULT true, "conversationRevision" TEXT, "revision" INTEGER NOT NULL DEFAULT 1, "expiresAt" TIMESTAMP(3) NOT NULL, "approvedAt" TIMESTAMP(3), "rejectedAt" TIMESTAMP(3), "actorUsuarioId" INTEGER, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceDraft_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceDraft_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDraft_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDraft_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDraft_empresaId_decisionId_fkey" FOREIGN KEY ("empresaId", "decisionId") REFERENCES "AICommerceDecision"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceDraft_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceDraft_empresaId_id_key" ON "AICommerceDraft"("empresaId", "id"); CREATE INDEX "AICommerceDraft_empresaId_conversationId_status_idx" ON "AICommerceDraft"("empresaId", "conversationId", "status"); CREATE INDEX "AICommerceDraft_empresaId_expiresAt_status_idx" ON "AICommerceDraft"("empresaId", "expiresAt", "status"); CREATE INDEX "AICommerceDraft_empresaId_retentionUntil_idx" ON "AICommerceDraft"("empresaId", "retentionUntil");

CREATE TABLE "AICommercePolicyDecision" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT NOT NULL, "conversationId" INTEGER, "draftId" TEXT, "action" TEXT NOT NULL DEFAULT 'UNSPECIFIED', "status" TEXT NOT NULL DEFAULT 'RECORDED', "reasonCode" TEXT, "detailsJson" TEXT NOT NULL DEFAULT '{}', "actorUsuarioId" INTEGER, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "occurredAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommercePolicyDecision_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommercePolicyDecision_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommercePolicyDecision_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommercePolicyDecision_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommercePolicyDecision_empresaId_draftId_fkey" FOREIGN KEY ("empresaId", "draftId") REFERENCES "AICommerceDraft"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommercePolicyDecision_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommercePolicyDecision_empresaId_id_key" ON "AICommercePolicyDecision"("empresaId", "id"); CREATE INDEX "AICommercePolicyDecision_empresaId_runId_occurredAt_idx" ON "AICommercePolicyDecision"("empresaId", "runId", "occurredAt"); CREATE INDEX "AICommercePolicyDecision_empresaId_draftId_occurredAt_idx" ON "AICommercePolicyDecision"("empresaId", "draftId", "occurredAt"); CREATE INDEX "AICommercePolicyDecision_empresaId_retentionUntil_idx" ON "AICommercePolicyDecision"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceHandoff" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "runId" TEXT, "conversationId" INTEGER, "draftId" TEXT,  "offerId" TEXT, "reason" TEXT NOT NULL DEFAULT 'UNSPECIFIED', "summarySanitized" TEXT, "queueKey" TEXT, "status" TEXT NOT NULL DEFAULT 'REQUESTED', "idempotencyKey" TEXT, "actorUsuarioId" INTEGER, "correlationId" TEXT, "eventJson" TEXT NOT NULL DEFAULT '{}', "revision" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "AICommerceHandoff_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceHandoff_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceHandoff_empresaId_runId_fkey" FOREIGN KEY ("empresaId", "runId") REFERENCES "AICommerceRun"("empresaId", "runId") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceHandoff_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceHandoff_empresaId_draftId_fkey" FOREIGN KEY ("empresaId", "draftId") REFERENCES "AICommerceDraft"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceHandoff_empresaId_offerId_fkey" FOREIGN KEY ("empresaId", "offerId") REFERENCES "ProductOffer"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceHandoff_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceHandoff_empresaId_id_key" ON "AICommerceHandoff"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceHandoff_empresaId_idempotencyKey_key" ON "AICommerceHandoff"("empresaId", "idempotencyKey") WHERE "idempotencyKey" IS NOT NULL; CREATE INDEX "AICommerceHandoff_empresaId_conversationId_status_idx" ON "AICommerceHandoff"("empresaId", "conversationId", "status"); CREATE INDEX "AICommerceHandoff_empresaId_retentionUntil_idx" ON "AICommerceHandoff"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceProductInterest" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "conversationId" INTEGER NOT NULL, "customerId" INTEGER, "offerId" TEXT NOT NULL, "catalogProductId" INTEGER NOT NULL, "desiredQuantity" DECIMAL, "preferencesJson" TEXT NOT NULL DEFAULT '{}', "status" TEXT NOT NULL DEFAULT 'REGISTERED', "source" TEXT NOT NULL DEFAULT 'HUMAN_APPROVED', "idempotencyKey" TEXT NOT NULL, "actorUsuarioId" INTEGER, "correlationId" TEXT, "revision" INTEGER NOT NULL DEFAULT 1, "eventJson" TEXT NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL, CONSTRAINT "AICommerceProductInterest_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceProductInterest_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceProductInterest_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceProductInterest_empresaId_customerId_fkey" FOREIGN KEY ("empresaId", "customerId") REFERENCES "Cliente"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceProductInterest_empresaId_offerId_fkey" FOREIGN KEY ("empresaId", "offerId") REFERENCES "ProductOffer"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceProductInterest_empresaId_catalogProductId_fkey" FOREIGN KEY ("empresaId", "catalogProductId") REFERENCES "CommercialCatalogProduct"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceProductInterest_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceProductInterest_empresaId_id_key" ON "AICommerceProductInterest"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceProductInterest_empresaId_idempotencyKey_key" ON "AICommerceProductInterest"("empresaId", "idempotencyKey"); CREATE INDEX "AICommerceProductInterest_empresaId_conversationId_status_idx" ON "AICommerceProductInterest"("empresaId", "conversationId", "status"); CREATE INDEX "AICommerceProductInterest_empresaId_offerId_createdAt_idx" ON "AICommerceProductInterest"("empresaId", "offerId", "createdAt"); CREATE INDEX "AICommerceProductInterest_empresaId_retentionUntil_idx" ON "AICommerceProductInterest"("empresaId", "retentionUntil");

CREATE TABLE "AICommerceOpportunityDraft" ("id" TEXT NOT NULL, "empresaId" INTEGER NOT NULL, "conversationId" INTEGER NOT NULL, "customerId" INTEGER, "primaryOfferId" TEXT, "catalogProductId" INTEGER, "offerIdsJson" TEXT NOT NULL DEFAULT '[]', "summarySanitized" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'DRAFT', "idempotencyKey" TEXT NOT NULL, "actorUsuarioId" INTEGER, "correlationId" TEXT, "revision" INTEGER NOT NULL DEFAULT 1, "eventJson" TEXT NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "retentionUntil" TIMESTAMP(3) NOT NULL, CONSTRAINT "AICommerceOpportunityDraft_pkey" PRIMARY KEY ("id"), CONSTRAINT "AICommerceOpportunityDraft_empresaId_fkey" FOREIGN KEY ("empresaId") REFERENCES "Empresa"("id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceOpportunityDraft_empresaId_conversationId_fkey" FOREIGN KEY ("empresaId", "conversationId") REFERENCES "ConversaCanal"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceOpportunityDraft_empresaId_customerId_fkey" FOREIGN KEY ("empresaId", "customerId") REFERENCES "Cliente"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceOpportunityDraft_empresaId_primaryOfferId_fkey" FOREIGN KEY ("empresaId", "primaryOfferId") REFERENCES "ProductOffer"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceOpportunityDraft_empresaId_catalogProductId_fkey" FOREIGN KEY ("empresaId", "catalogProductId") REFERENCES "CommercialCatalogProduct"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT "AICommerceOpportunityDraft_empresaId_actorUsuarioId_fkey" FOREIGN KEY ("empresaId", "actorUsuarioId") REFERENCES "Usuario"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE UNIQUE INDEX "AICommerceOpportunityDraft_empresaId_id_key" ON "AICommerceOpportunityDraft"("empresaId", "id"); CREATE UNIQUE INDEX "AICommerceOpportunityDraft_empresaId_idempotencyKey_key" ON "AICommerceOpportunityDraft"("empresaId", "idempotencyKey"); CREATE INDEX "AICommerceOpportunityDraft_empresaId_conversationId_status_idx" ON "AICommerceOpportunityDraft"("empresaId", "conversationId", "status"); CREATE INDEX "AICommerceOpportunityDraft_empresaId_retentionUntil_idx" ON "AICommerceOpportunityDraft"("empresaId", "retentionUntil");



ALTER TABLE "AICommerceHandoff" ADD CONSTRAINT "AICommerceHandoff_empresaId_opportunityDraftId_fkey" FOREIGN KEY ("empresaId", "opportunityDraftId") REFERENCES "AICommerceOpportunityDraft"("empresaId", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

COMMIT;
