ALTER TABLE "Cliente" ADD COLUMN "cidade" TEXT;
ALTER TABLE "Cliente" ADD COLUMN "estado" TEXT;
ALTER TABLE "Cliente" ADD COLUMN "cpfCnpj" TEXT;
ALTER TABLE "Cliente" ADD COLUMN "revisao" INTEGER NOT NULL DEFAULT 1;
